### PR TITLE
Fix compilation error in tests.

### PR DESCRIPTION
**Pull request by vext01**
Another compilation error that somehow slipped CI. I don't get it...

Did we perhaps manually merge in a time where CI was down?

### CODE REVIEW

**Comment by ptersilie** [comment]
I'm as baffled as you are.

**Comment by bjorn3** [comment]
That line was introduced in https://github.com/softdevteam/hwtracer/pull/87, which passed CI. I even checked that it ran `cargo test` and that tests for the `perf_pt` backend ran.

**Comment by vext01** [comment]
Odd.... Let's keep an eye on this.

**Comment by bjorn3** [comment]
I found the culprit. This repo doesn't have a `Cargo.lock` checked in and at the same time uses a git dependency on https://github.com/softdevteam/phdrs without pinning a commit. This meant that when https://github.com/softdevteam/phdrs/pull/5 was merged, the next CI run on this repo picked it up. That PR was a breaking change, which meant that CI on this repo broke. You should either check in `Cargo.lock` or pin the git dependency to a specific commit. (`rev =` I think)

**Comment by ltratt** [comment]
Yes, `rev` in `Cargo.toml` also works: IMHO that's the preferred route, because it's robust to `Cargo.lock` changes.

**Comment by vext01** [comment]
> the next CI run on this repo picked it up

I don't get this part. The CI destroys the build directory between builds:

```
buildbot_sh_factory.addStep(steps.Git(repourl=get_repourl,
                                      mode='full', method='clobber', # Start fresh each time.
                                      shallow=True))
```

http://docs.buildbot.net/current/manual/configuration/buildsteps.html#git

**Comment by bjorn3** [comment]
`Cargo.lock` has to be regenerated on every CI run. Cargo chooses the HEAD commit in https://github.com/softdevteam/phdrs for the `phdrs` dependency when it needs to generate `Cargo.lock` as there is no `rev` specification.
